dist: trusty
sudo: required
language: rust
rust:
  - stable
  - nightly
  - 1.27.0
addons:
  apt:
    packages:
      - build-essential
      - libncurses5-dev
      - libncursesw5-dev
      - libsqlite3-dev
      - libssl-dev
      - pkg-config
      - yasm
matrix:
  allow_failures:
    - rust: nightly
cache: cargo
script:
  - (git clone --depth 1 -b "release/3.4" https://github.com/FFmpeg/FFmpeg.git && cd FFmpeg && ./configure --enable-shared && make --jobs=2 && sudo make install --jobs=2 && sudo ldconfig)
  - cargo build --verbose --all
  - cargo test --verbose --all
  - 'if [ $TRAVIS_RUST_VERSION = nightly ]; then cargo bench --verbose --all; fi'
