dist: trusty
sudo: required
addons:
  apt:
    packages:
      - build-essential
      - libncurses5-dev
      - libncursesw5-dev
      - libsqlite3-dev
      - libssl-dev
      - pkg-config
      - yasm
matrix:
  include:
    - language: rust
      rust: stable
      env: FFMPEG_VERSION=3.4.4
      install:
        - ci/install-ffmpeg.sh
      script:
        - ci/script-rust.sh
    - language: rust
      rust: nightly
      env: FFMPEG_VERSION=3.4.4
      install:
        - ci/install-ffmpeg.sh
      script:
        - ci/script-rust.sh
    - language: rust
      rust: 1.30.0
      env: FFMPEG_VERSION=3.4.4
      install:
        - ci/install-ffmpeg.sh
      script:
        - ci/script-rust.sh
    - language: node_js
      node_js: "node"
      script:
        - yarn
        - yarn build
        - node_modules/eslint/bin/eslint.js ui-src
    - language: node_js
      node_js: "8"
      script:
        - yarn
        - yarn build
        - node_modules/eslint/bin/eslint.js ui-src
  allow_failures:
    - rust: nightly
cache:
  cargo: true
  yarn: true
  directories:
    - ffmpeg-3.4.4
  timeout: 600
