dist: bionic
addons:
  apt:
    packages:
      - build-essential
      - libavcodec-dev
      - libavformat-dev
      - libavutil-dev
      - libncurses5-dev
      - libncursesw5-dev
      - libsqlite3-dev
      - libssl-dev
      - pkgconf
      - yasm
matrix:
  include:
    - language: rust
      rust: stable
      script:
        - ci/script-rust.sh
    - language: rust
      rust: nightly
      script:
        - ci/script-rust.sh
    - language: rust
      rust: 1.45.0
      script:
        - ci/script-rust.sh
    - language: node_js
      node_js: "node"
      script:
        - yarn
        - yarn build
        - yarn lint
    - language: node_js
      node_js: "lts/*"
      script:
        - yarn
        - yarn build
        - yarn lint
  allow_failures:
    - rust: nightly
cache:
  cargo: true
  yarn: true
  timeout: 600
