dist: trusty
sudo: required
language: rust
rust:
  - stable
  - nightly
  - 1.27.0
addons:
  apt:
    packages:
      - build-essential
      - libncurses5-dev
      - libncursesw5-dev
      - libsqlite3-dev
      - libssl-dev
      - pkg-config
      - yasm
matrix:
  allow_failures:
    - rust: nightly
cache:
  cargo: true
  directories:
    - ffmpeg-3.4.4
  timeout: 600
install:
  - test -f ffmpeg-3.4.4/configure || (wget https://ffmpeg.org/releases/ffmpeg-3.4.4.tar.xz && tar xf ffmpeg-3.4.4.tar.xz)
  - pushd ffmpeg-3.4.4 && ./configure --enable-shared && make --jobs=2 && sudo make install --jobs=2&& sudo ldconfig && rm -f ffbuild/config.log && popd
script:
  - cargo build --all
  - cargo test --all
  - 'if [ $TRAVIS_RUST_VERSION = nightly ]; then cargo bench --all; fi'
