[package]
name = "moonfire-nvr"
version = "0.1.0"
authors = ["Scott Lamb <slamb@slamb.org>"]

[features]

# The nightly feature is used within moonfire-nvr itself to gate the
# benchmarks. Also pass it along to crates that can benefit from it.
nightly = ["parking_lot/nightly"]

# The bundled feature includes bundled (aka statically linked) versions of
# native libraries where possible.
bundled = ["rusqlite/bundled"]

[dependencies]
byteorder = "1.0"
docopt = "0.8"
futures = "0.1"
fnv = "1.0"
http-entity = { git = "https://github.com/scottlamb/http-entity", branch = "hyper-0.11.x" }
hyper = { git = "https://github.com/scottlamb/hyper", branch = "moonfire-on-0.11.x" }
lazy_static = "0.2"
libc = "0.2"
log = { version = "0.3", features = ["release_max_level_info"] }
lru-cache = "0.1"
memmap = "0.5"
mime = "0.3"
mylog = { git = "https://github.com/scottlamb/mylog" }
openssl = "0.9"
parking_lot = { version = "0.4", features = [] }
reffers = { git = "https://github.com/diwic/reffers-rs" }
regex = "0.2"
rusqlite = "0.12"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
smallvec = "0.4"
time = "0.1"
tokio-core = "0.1"
tokio-signal = "0.1"
url = "1.4"
uuid = { version = "0.5", features = ["serde", "v4"] }

[dev-dependencies]
reqwest = "0.6"
tempdir = "0.3"

[dependencies.cursive]
version = "0.5"
#default-features = false
#features = ["termion"]

[dependencies.ffmpeg]
git = "https://github.com/scottlamb/rust-ffmpeg"
branch = "2.x"
default-features = false
features = ["codec", "format"]

[dependencies.ffmpeg-sys]
version = "2.8"
default-features = false
features = ["avcodec"]

[profile.release]
debug = true

[profile.bench]
debug = true

[replace]
"https://github.com/hyperium/hyper#hyper:0.11.0-a.0" = { git = "https://github.com/scottlamb/hyper", branch = "moonfire-on-0.11.x" }
"hyper:0.10.12" = { git = "https://github.com/scottlamb/hyper", branch = "moonfire-on-0.10.x" }
