[package]
name = "moonfire-nvr"
version = "0.1.0"
authors = ["Scott Lamb <slamb@slamb.org>"]
build = "build.rs"

[features]
nightly = []

[dependencies]
byteorder = "0.5"
chan = "0.1"
chan-signal = "0.1"
docopt = "0.6"
fnv = "1.0"
hyper = "0.9"
lazy_static = "0.2"
libc = "0.2"
log = { version = "0.3", features = ["release_max_level_info"] }
lru-cache = "0.1"
memmap = "0.3"
mime = "0.2"
openssl = "0.8"
regex = "0.1"
rusqlite = "0.7"
rustc-serialize = "0.3"
serde = "0.8"
serde_json = "0.8"
slog = "1.2"
slog-envlogger = "0.5"
slog-stdlog = "1.1"
slog-term = "1.3"
smallvec = "0.2"
time = "0.1"
url = "1.2"
uuid = { version = "0.3", features = ["serde", "v4"] }

[build-dependencies]
serde_codegen = "0.8"

[dev-dependencies]
tempdir = "0.3"

[dependencies.ffmpeg]
git = "https://github.com/scottlamb/rust-ffmpeg"
branch = "2.x"
default-features = false
features = ["codec", "format"]

[dependencies.ffmpeg-sys]
version = "2.8"
default-features = false
features = ["avcodec"]

[profile.release]
lto = true
debug = true

[profile.bench]
lto = true
debug = true
