[package]
name = "moonfire-nvr"
version = "0.1.0"
authors = ["Scott Lamb <slamb@slamb.org>"]

[features]

# The nightly feature is used within moonfire-nvr itself to gate the
# benchmarks. Also pass it along to crates that can benefit from it.
nightly = ["parking_lot/nightly"]

# The bundled feature includes bundled (aka statically linked) versions of
# native libraries where possible.
bundled = ["rusqlite/bundled"]

[dependencies]
byteorder = "1.0"
docopt = "0.8"
futures = "0.1"
futures-cpupool = "0.1"
fnv = "1.0"
http-serve = { git = "https://github.com/scottlamb/http-serve" }
hyper = "0.11.16"
lazy_static = "1.0"
libc = "0.2"
log = { version = "0.4", features = ["release_max_level_info"] }
lru-cache = "0.1"
memmap = "0.6"
mime = "0.3"
moonfire-ffmpeg = { path = "ffmpeg" }
mylog = { git = "https://github.com/scottlamb/mylog" }
openssl = "0.10"
parking_lot = { version = "0.5", features = [] }
reffers = { git = "https://github.com/diwic/reffers-rs" }
regex = "0.2"
rusqlite = "0.13"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
smallvec = "0.6"
time = "0.1"
tokio-core = "0.1"
tokio-signal = "0.1"
url = "1.4"
uuid = { version = "0.5", features = ["serde", "v4"] }

[dev-dependencies]
reqwest = "0.8"
tempdir = "0.3"

[dependencies.cursive]
version = "0.7"
#default-features = false
#features = ["termion-backend"]

[profile.release]
debug = true

[profile.bench]
debug = true

[replace]

# This hyper fork has a patch to disable Nagle's algorithm.
"hyper:0.11.16" = { git = "https://github.com/scottlamb/hyper", branch = "moonfire-on-0.11.x" }
