[package]
name = "moonfire-nvr"
version = "0.1.0"
authors = ["Scott Lamb <slamb@slamb.org>"]

[features]
nightly = []

[dependencies]
byteorder = "1.0"
chan = "0.1"
chan-signal = "0.2"
docopt = "0.7"
fnv = "1.0"
http-entity = { git = "https://github.com/scottlamb/http-entity" }
hyper = "0.10"
lazy_static = "0.2"
libc = "0.2"
log = { version = "0.3", features = ["release_max_level_info"] }
lru-cache = "0.1"
memmap = "0.5"
mime = "0.2"
openssl = "0.9"
regex = "0.2"
rusqlite = "0.9"
rustc-serialize = "0.3"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
slog = "1.4"
slog-envlogger = "0.5"
slog-stdlog = "1.1"
slog-term = "1.3"
smallvec = "0.3"
time = "0.1"
url = "1.4"
uuid = { version = "0.4", features = ["serde", "v4"] }

[dev-dependencies]
tempdir = "0.3"

[dependencies.cursive]
version = "0.4"
#default-features = false
#features = ["termion"]

[dependencies.ffmpeg]
git = "https://github.com/scottlamb/rust-ffmpeg"
branch = "2.x"
default-features = false
features = ["codec", "format"]

[dependencies.ffmpeg-sys]
version = "2.8"
default-features = false
features = ["avcodec"]

[profile.release]
lto = true
debug = true

[profile.bench]
lto = true
debug = true
