[package]
name = "moonfire-db"
version = "0.0.1"
authors = ["Scott Lamb <slamb@slamb.org>"]
readme = "../README.md"

[features]
nightly = []

[lib]
path = "lib.rs"

[dependencies]
failure = "0.1.1"
fnv = "1.0"
lazy_static = "1.0"
libc = "0.2"
log = "0.4"
lru-cache = "0.1"
moonfire-base = { path = "../base" }
mylog = { git = "https://github.com/scottlamb/mylog" }
openssl = "0.10"
parking_lot = { version = "0.6", features = [] }
protobuf = "2.0"
regex = "1.0"
rusqlite = "0.14"
tempdir = "0.3"
time = "0.1"
uuid = { version = "0.6", features = ["std", "v4"] }
